accelerator: null
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
attack: false
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
automatic_optimization: null
batch_size: 256
benchmark: false
binary: true
check_val_every_n_epoch: 1
checkpoint: null
checkpoint_callback: true
data_dir: .
dataset: mnist
default_root_dir: null
deterministic: false
distributed_backend: null
enable_pl_optimizer: null
enc_out_dim: 1024
enc_type: mnist_conv
eps: 0.1
fast_dev_run: false
first_conv: false
flush_logs_every_n_steps: 100
gpus: 1
gradient_clip_val: 0
input_channels: 1
input_height: 28
k: 10
kl_coeff: 1.0
latent_dim: 64
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr: 0.0001
max_epochs: null
max_steps: null
maxpool1: false
min_epochs: null
min_steps: null
mlp_hidden_dim: 500
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
name: binary
no_decoder: false
num_classes: 10
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 8
overfit_batches: 0.0
per_class: false
plugins: null
precision: 32
prepare_data_per_node: true
pretrained: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
py_mode: 0
recon_loss_type: l2
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
stochastic_weight_avg: false
sync_batchnorm: false
terminate_on_nan: false
test: false
tpu_cores: !!python/name:pytorch_lightning.utilities.argparse._gpus_arg_default ''
track_grad_norm: -1
truncated_bptt_steps: null
vae_type: gfz
val_check_interval: 1.0
weights_save_path: null
weights_summary: top
